-- DROP TABLE DEPT;
CREATE TABLE DEPT
       (DEPTNO NUMBER PRIMARY KEY,
        DNAME VARCHAR2(64),
        LOC VARCHAR2(64) );

CREATE TABLE EMP
       (EMPNO NUMBER PRIMARY KEY,
        ENAME VARCHAR2(64),
        JOB VARCHAR2(64),
        HIREDATE DATE,
        DEPTNO NUMBER,
        CONSTRAINT EMP_DEPT_FK FOREIGN KEY (DEPTNO) REFERENCES DEPT(DEPTNO));

INSERT INTO DEPT VALUES (10, 'ACCOUNTING', 'NEW YORK');
INSERT INTO DEPT VALUES (20, 'RESEARCH',   'ORACLE');
INSERT INTO DEPT VALUES (30, 'SALES',      'CHICAGO');
INSERT INTO DEPT VALUES (40, 'OPERATIONS', 'BOSTON');

INSERT INTO EMP VALUES (7369, 'SMITH',  'CLERK', DATE '1980-12-17', 20);
INSERT INTO EMP VALUES (7499, 'ALLEN',  'SALESMAN', DATE '2000-02-20', 30);
INSERT INTO EMP VALUES (7521, 'WARD',   'SALESMAN', DATE '2000-02-22', 30);
INSERT INTO EMP VALUES (7566, 'JONES',  'MANAGER', DATE '2009-04-02', 20);
INSERT INTO EMP VALUES (7698, 'BLAKE',  'MANAGER', DATE '2015-05-01', 30);
INSERT INTO EMP VALUES (7782, 'CLARK',  'MANAGER', DATE '2025-06-09', 10);
COMMIT;

EXIT